#ifndef __TRADE_EVENT_CODE_H__
#define __TRADE_EVENT_CODE_H__


enum
{
	MSG_STATUS_NO_UPDATE      = -5001,
	MSG_STATUS_UPDATED        = 0,
	MSG_STATUS_NO_PERMISSION  = -5003,
	MSG_STATUS_NOT_EXIST      = -5004,
	MSG_STATUS_INIT_FAILED    = -5005,
};

enum
{
	RET_HAS_LOGIN			  = -4999,
	RET_HAS_INIT			  = -4998,
	RET_NOT_LOGIN			  = -4900,
	RET_NOT_INIT			  = -4901,
}; 

enum
{
	RET_DROPDOWN			  = -89999,
};

enum
{
	RET_SUCCEED				  = 0,

	RET_ERR_QUANTITY          = -4901,
	RET_ERR_SLPRICE			  = -4902,
	RET_ERR_TPPRICE			  = -4903,
	RET_ERR_OPENDIECTOR		  = -4904,
	RET_ERR_CLOSEDIRECTOR	  = -4905,		
	RET_ERR_TRADERANGE		  = -4906,
	RET_ERR_OPERATETYPE		  = -4907,
	RET_ERR_INOUTAMOUNT		  = -4908,
	RET_ERR_COMMODITYRIGHT	  = -4909,
	RET_ERR_COMMODITYID		  = -4910,
	RET_ERR_NOHOLDPOSITION    = -4911,

	RET_ERR_RESPONETIMEOUT	  = -4888,
};


enum
{
	EVENT_CODE_LOGIN               =   1,
	EVENT_CODE_QUOTE               =   2,
	EVENT_CODE_INITIALIZE          =   3,

	EVENT_CODE_OPENMARKETORDER     =   4,
	EVENT_CODE_CLOSEMARKETORDER    =   5,
	EVENT_CODE_OPENLIMITORDER      =   6,
	EVENT_CODE_LIMITCLOSEPOSITION  =   7,
	EVENT_CODE_LIMITREVOKE         =   8,
	EVENT_CODE_SYSBULLETIN         =   9,
	EVENT_CODE_DISCONNECT          =  10,
	EVENT_CODE_SYSBUL_LIMITCLOSE   =  11,
	EVENT_CODE_SYSBUL_LIQUIDATION  =  12,
	EVENT_CODE_MONEYINOUT		   =  13,
	EVENT_CODE_MONEYQUERY		   =  14,
    EVENT_CODE_HEARTBEAT            =  15,
};

#endif
